-- Sample input data:
-- employees table:
-- | first_name | last_name |
-- |-----------|-----------|
-- | John      | John      |
-- | Jane      | Doe       |
-- | John      | Smith     |
-- | Jane      | Jane      |

-- Sample output:
-- | first_name | last_name |
-- |-----------|-----------|
-- | John      | John      |
-- | Jane      | Jane      |
