-- Sample input data:
-- employees table:
-- | department | employee_id |
-- |-----------|------------|
-- | Sales      | 1          |
-- | Sales      | 2          |
-- | Sales      | 3          |
-- | Marketing  | 4          |
-- | Marketing  | 5          |
-- | IT         | 6          |

-- Sample output:
-- | department |
-- |-----------|
-- | Sales      |
